RULES:
  blue:
    name: "client"
    priority: 100
    path_pattern:
      - "/"
    host_header:
      - "blue.example.com"
  green:
    name: "api"
    priority: 200
    path_pattern:
      - "/"
    host_header:
      - "example.com"