- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - "./vars/variables.yml"
  tasks: 
  - name: 1.0 -- Update AMI in Launch Template
    shell: aws ec2 create-launch-template-version \
            --region {{ aws_region }} \
            --launch-template-id {{ launch_template_id }} \
            --version-description "AMI Build by Packer" \
            --source-version {{ source_version }} \
            --launch-template-data '{"ImageId":"{{ ami_id }}"}'
    register: lt_result
  - set_fact:
      lt_json: "{{ lt_result.stdout | from_json }}"
  - debug: msg="{{ lt_json }}"

  - name: 1.1 -- Update Auto Scaling Group
    shell: aws autoscaling update-auto-scaling-group \
            --region {{ aws_region }} \
            --auto-scaling-group-name {{ asg_name }} \
            --launch-template LaunchTemplateName={{ lt_json.LaunchTemplateVersion.LaunchTemplateName }},Version={{ lt_json.LaunchTemplateVersion.VersionNumber }}